[package]
name = "storfad"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "storfad"
path = "src/bin/main.rs"

[dependencies]
bytes = "1.3.0"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros", "fs", "io-util"] }
